version: '3.8'

volumes:
  activemq-data:
    driver: local

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: book_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Веб-интерфейс
    volumes:
      - activemq-data:/opt/activemq/data
